/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: timer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "timer.pb-c.h"
void   timerpb__timer_health__init
                     (Timerpb__TimerHealth         *message)
{
  static const Timerpb__TimerHealth init_value = TIMERPB__TIMER_HEALTH__INIT;
  *message = init_value;
}
size_t timerpb__timer_health__get_packed_size
                     (const Timerpb__TimerHealth *message)
{
  assert(message->base.descriptor == &timerpb__timer_health__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_health__pack
                     (const Timerpb__TimerHealth *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_health__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_health__pack_to_buffer
                     (const Timerpb__TimerHealth *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_health__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerHealth *
       timerpb__timer_health__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerHealth *)
     protobuf_c_message_unpack (&timerpb__timer_health__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_health__free_unpacked
                     (Timerpb__TimerHealth *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_health__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_pulse__init
                     (Timerpb__TimerPulse         *message)
{
  static const Timerpb__TimerPulse init_value = TIMERPB__TIMER_PULSE__INIT;
  *message = init_value;
}
size_t timerpb__timer_pulse__get_packed_size
                     (const Timerpb__TimerPulse *message)
{
  assert(message->base.descriptor == &timerpb__timer_pulse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_pulse__pack
                     (const Timerpb__TimerPulse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_pulse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_pulse__pack_to_buffer
                     (const Timerpb__TimerPulse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_pulse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerPulse *
       timerpb__timer_pulse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerPulse *)
     protobuf_c_message_unpack (&timerpb__timer_pulse__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_pulse__free_unpacked
                     (Timerpb__TimerPulse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_pulse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_pin__init
                     (Timerpb__TimerPin         *message)
{
  static const Timerpb__TimerPin init_value = TIMERPB__TIMER_PIN__INIT;
  *message = init_value;
}
size_t timerpb__timer_pin__get_packed_size
                     (const Timerpb__TimerPin *message)
{
  assert(message->base.descriptor == &timerpb__timer_pin__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_pin__pack
                     (const Timerpb__TimerPin *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_pin__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_pin__pack_to_buffer
                     (const Timerpb__TimerPin *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_pin__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerPin *
       timerpb__timer_pin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerPin *)
     protobuf_c_message_unpack (&timerpb__timer_pin__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_pin__free_unpacked
                     (Timerpb__TimerPin *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_pin__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__gps_tick_xref__init
                     (Timerpb__GpsTickXref         *message)
{
  static const Timerpb__GpsTickXref init_value = TIMERPB__GPS_TICK_XREF__INIT;
  *message = init_value;
}
size_t timerpb__gps_tick_xref__get_packed_size
                     (const Timerpb__GpsTickXref *message)
{
  assert(message->base.descriptor == &timerpb__gps_tick_xref__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__gps_tick_xref__pack
                     (const Timerpb__GpsTickXref *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__gps_tick_xref__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__gps_tick_xref__pack_to_buffer
                     (const Timerpb__GpsTickXref *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__gps_tick_xref__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__GpsTickXref *
       timerpb__gps_tick_xref__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__GpsTickXref *)
     protobuf_c_message_unpack (&timerpb__gps_tick_xref__descriptor,
                                allocator, len, data);
}
void   timerpb__gps_tick_xref__free_unpacked
                     (Timerpb__GpsTickXref *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__gps_tick_xref__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_time_stamp__init
                     (Timerpb__TimerTimeStamp         *message)
{
  static const Timerpb__TimerTimeStamp init_value = TIMERPB__TIMER_TIME_STAMP__INIT;
  *message = init_value;
}
size_t timerpb__timer_time_stamp__get_packed_size
                     (const Timerpb__TimerTimeStamp *message)
{
  assert(message->base.descriptor == &timerpb__timer_time_stamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_time_stamp__pack
                     (const Timerpb__TimerTimeStamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_time_stamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_time_stamp__pack_to_buffer
                     (const Timerpb__TimerTimeStamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_time_stamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerTimeStamp *
       timerpb__timer_time_stamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerTimeStamp *)
     protobuf_c_message_unpack (&timerpb__timer_time_stamp__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_time_stamp__free_unpacked
                     (Timerpb__TimerTimeStamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_time_stamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_data__init
                     (Timerpb__TimerData         *message)
{
  static const Timerpb__TimerData init_value = TIMERPB__TIMER_DATA__INIT;
  *message = init_value;
}
size_t timerpb__timer_data__get_packed_size
                     (const Timerpb__TimerData *message)
{
  assert(message->base.descriptor == &timerpb__timer_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_data__pack
                     (const Timerpb__TimerData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_data__pack_to_buffer
                     (const Timerpb__TimerData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerData *
       timerpb__timer_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerData *)
     protobuf_c_message_unpack (&timerpb__timer_data__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_data__free_unpacked
                     (Timerpb__TimerData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_data_list__init
                     (Timerpb__TimerDataList         *message)
{
  static const Timerpb__TimerDataList init_value = TIMERPB__TIMER_DATA_LIST__INIT;
  *message = init_value;
}
size_t timerpb__timer_data_list__get_packed_size
                     (const Timerpb__TimerDataList *message)
{
  assert(message->base.descriptor == &timerpb__timer_data_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_data_list__pack
                     (const Timerpb__TimerDataList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_data_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_data_list__pack_to_buffer
                     (const Timerpb__TimerDataList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_data_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerDataList *
       timerpb__timer_data_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerDataList *)
     protobuf_c_message_unpack (&timerpb__timer_data_list__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_data_list__free_unpacked
                     (Timerpb__TimerDataList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_data_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__elapsed_config__init
                     (Timerpb__ElapsedConfig         *message)
{
  static const Timerpb__ElapsedConfig init_value = TIMERPB__ELAPSED_CONFIG__INIT;
  *message = init_value;
}
size_t timerpb__elapsed_config__get_packed_size
                     (const Timerpb__ElapsedConfig *message)
{
  assert(message->base.descriptor == &timerpb__elapsed_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__elapsed_config__pack
                     (const Timerpb__ElapsedConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__elapsed_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__elapsed_config__pack_to_buffer
                     (const Timerpb__ElapsedConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__elapsed_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__ElapsedConfig *
       timerpb__elapsed_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__ElapsedConfig *)
     protobuf_c_message_unpack (&timerpb__elapsed_config__descriptor,
                                allocator, len, data);
}
void   timerpb__elapsed_config__free_unpacked
                     (Timerpb__ElapsedConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__elapsed_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_config__init
                     (Timerpb__TimerConfig         *message)
{
  static const Timerpb__TimerConfig init_value = TIMERPB__TIMER_CONFIG__INIT;
  *message = init_value;
}
size_t timerpb__timer_config__get_packed_size
                     (const Timerpb__TimerConfig *message)
{
  assert(message->base.descriptor == &timerpb__timer_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_config__pack
                     (const Timerpb__TimerConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_config__pack_to_buffer
                     (const Timerpb__TimerConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerConfig *
       timerpb__timer_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerConfig *)
     protobuf_c_message_unpack (&timerpb__timer_config__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_config__free_unpacked
                     (Timerpb__TimerConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_config_ramp_photo_eye__init
                     (Timerpb__TimerConfigRampPhotoEye         *message)
{
  static const Timerpb__TimerConfigRampPhotoEye init_value = TIMERPB__TIMER_CONFIG_RAMP_PHOTO_EYE__INIT;
  *message = init_value;
}
size_t timerpb__timer_config_ramp_photo_eye__get_packed_size
                     (const Timerpb__TimerConfigRampPhotoEye *message)
{
  assert(message->base.descriptor == &timerpb__timer_config_ramp_photo_eye__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_config_ramp_photo_eye__pack
                     (const Timerpb__TimerConfigRampPhotoEye *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_config_ramp_photo_eye__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_config_ramp_photo_eye__pack_to_buffer
                     (const Timerpb__TimerConfigRampPhotoEye *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_config_ramp_photo_eye__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerConfigRampPhotoEye *
       timerpb__timer_config_ramp_photo_eye__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerConfigRampPhotoEye *)
     protobuf_c_message_unpack (&timerpb__timer_config_ramp_photo_eye__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_config_ramp_photo_eye__free_unpacked
                     (Timerpb__TimerConfigRampPhotoEye *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_config_ramp_photo_eye__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_config_lane_photo_eye__init
                     (Timerpb__TimerConfigLanePhotoEye         *message)
{
  static const Timerpb__TimerConfigLanePhotoEye init_value = TIMERPB__TIMER_CONFIG_LANE_PHOTO_EYE__INIT;
  *message = init_value;
}
size_t timerpb__timer_config_lane_photo_eye__get_packed_size
                     (const Timerpb__TimerConfigLanePhotoEye *message)
{
  assert(message->base.descriptor == &timerpb__timer_config_lane_photo_eye__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_config_lane_photo_eye__pack
                     (const Timerpb__TimerConfigLanePhotoEye *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_config_lane_photo_eye__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_config_lane_photo_eye__pack_to_buffer
                     (const Timerpb__TimerConfigLanePhotoEye *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_config_lane_photo_eye__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerConfigLanePhotoEye *
       timerpb__timer_config_lane_photo_eye__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerConfigLanePhotoEye *)
     protobuf_c_message_unpack (&timerpb__timer_config_lane_photo_eye__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_config_lane_photo_eye__free_unpacked
                     (Timerpb__TimerConfigLanePhotoEye *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_config_lane_photo_eye__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_config_opposed_starter__init
                     (Timerpb__TimerConfigOpposedStarter         *message)
{
  static const Timerpb__TimerConfigOpposedStarter init_value = TIMERPB__TIMER_CONFIG_OPPOSED_STARTER__INIT;
  *message = init_value;
}
size_t timerpb__timer_config_opposed_starter__get_packed_size
                     (const Timerpb__TimerConfigOpposedStarter *message)
{
  assert(message->base.descriptor == &timerpb__timer_config_opposed_starter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_config_opposed_starter__pack
                     (const Timerpb__TimerConfigOpposedStarter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_config_opposed_starter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_config_opposed_starter__pack_to_buffer
                     (const Timerpb__TimerConfigOpposedStarter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_config_opposed_starter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerConfigOpposedStarter *
       timerpb__timer_config_opposed_starter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerConfigOpposedStarter *)
     protobuf_c_message_unpack (&timerpb__timer_config_opposed_starter__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_config_opposed_starter__free_unpacked
                     (Timerpb__TimerConfigOpposedStarter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_config_opposed_starter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_config_opposed_position__init
                     (Timerpb__TimerConfigOpposedPosition         *message)
{
  static const Timerpb__TimerConfigOpposedPosition init_value = TIMERPB__TIMER_CONFIG_OPPOSED_POSITION__INIT;
  *message = init_value;
}
size_t timerpb__timer_config_opposed_position__get_packed_size
                     (const Timerpb__TimerConfigOpposedPosition *message)
{
  assert(message->base.descriptor == &timerpb__timer_config_opposed_position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_config_opposed_position__pack
                     (const Timerpb__TimerConfigOpposedPosition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_config_opposed_position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_config_opposed_position__pack_to_buffer
                     (const Timerpb__TimerConfigOpposedPosition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_config_opposed_position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerConfigOpposedPosition *
       timerpb__timer_config_opposed_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerConfigOpposedPosition *)
     protobuf_c_message_unpack (&timerpb__timer_config_opposed_position__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_config_opposed_position__free_unpacked
                     (Timerpb__TimerConfigOpposedPosition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_config_opposed_position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_event_list__init
                     (Timerpb__TimerEventList         *message)
{
  static const Timerpb__TimerEventList init_value = TIMERPB__TIMER_EVENT_LIST__INIT;
  *message = init_value;
}
size_t timerpb__timer_event_list__get_packed_size
                     (const Timerpb__TimerEventList *message)
{
  assert(message->base.descriptor == &timerpb__timer_event_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_event_list__pack
                     (const Timerpb__TimerEventList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_event_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_event_list__pack_to_buffer
                     (const Timerpb__TimerEventList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_event_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerEventList *
       timerpb__timer_event_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerEventList *)
     protobuf_c_message_unpack (&timerpb__timer_event_list__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_event_list__free_unpacked
                     (Timerpb__TimerEventList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_event_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__timer_event__init
                     (Timerpb__TimerEvent         *message)
{
  static const Timerpb__TimerEvent init_value = TIMERPB__TIMER_EVENT__INIT;
  *message = init_value;
}
size_t timerpb__timer_event__get_packed_size
                     (const Timerpb__TimerEvent *message)
{
  assert(message->base.descriptor == &timerpb__timer_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__timer_event__pack
                     (const Timerpb__TimerEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__timer_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__timer_event__pack_to_buffer
                     (const Timerpb__TimerEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__timer_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__TimerEvent *
       timerpb__timer_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__TimerEvent *)
     protobuf_c_message_unpack (&timerpb__timer_event__descriptor,
                                allocator, len, data);
}
void   timerpb__timer_event__free_unpacked
                     (Timerpb__TimerEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__timer_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__event_race_paddle_drop__init
                     (Timerpb__EventRacePaddleDrop         *message)
{
  static const Timerpb__EventRacePaddleDrop init_value = TIMERPB__EVENT_RACE_PADDLE_DROP__INIT;
  *message = init_value;
}
size_t timerpb__event_race_paddle_drop__get_packed_size
                     (const Timerpb__EventRacePaddleDrop *message)
{
  assert(message->base.descriptor == &timerpb__event_race_paddle_drop__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__event_race_paddle_drop__pack
                     (const Timerpb__EventRacePaddleDrop *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__event_race_paddle_drop__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__event_race_paddle_drop__pack_to_buffer
                     (const Timerpb__EventRacePaddleDrop *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__event_race_paddle_drop__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__EventRacePaddleDrop *
       timerpb__event_race_paddle_drop__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__EventRacePaddleDrop *)
     protobuf_c_message_unpack (&timerpb__event_race_paddle_drop__descriptor,
                                allocator, len, data);
}
void   timerpb__event_race_paddle_drop__free_unpacked
                     (Timerpb__EventRacePaddleDrop *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__event_race_paddle_drop__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__event_timer_availability__init
                     (Timerpb__EventTimerAvailability         *message)
{
  static const Timerpb__EventTimerAvailability init_value = TIMERPB__EVENT_TIMER_AVAILABILITY__INIT;
  *message = init_value;
}
size_t timerpb__event_timer_availability__get_packed_size
                     (const Timerpb__EventTimerAvailability *message)
{
  assert(message->base.descriptor == &timerpb__event_timer_availability__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__event_timer_availability__pack
                     (const Timerpb__EventTimerAvailability *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__event_timer_availability__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__event_timer_availability__pack_to_buffer
                     (const Timerpb__EventTimerAvailability *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__event_timer_availability__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__EventTimerAvailability *
       timerpb__event_timer_availability__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__EventTimerAvailability *)
     protobuf_c_message_unpack (&timerpb__event_timer_availability__descriptor,
                                allocator, len, data);
}
void   timerpb__event_timer_availability__free_unpacked
                     (Timerpb__EventTimerAvailability *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__event_timer_availability__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__event_timer_health_alert__init
                     (Timerpb__EventTimerHealthAlert         *message)
{
  static const Timerpb__EventTimerHealthAlert init_value = TIMERPB__EVENT_TIMER_HEALTH_ALERT__INIT;
  *message = init_value;
}
size_t timerpb__event_timer_health_alert__get_packed_size
                     (const Timerpb__EventTimerHealthAlert *message)
{
  assert(message->base.descriptor == &timerpb__event_timer_health_alert__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__event_timer_health_alert__pack
                     (const Timerpb__EventTimerHealthAlert *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__event_timer_health_alert__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__event_timer_health_alert__pack_to_buffer
                     (const Timerpb__EventTimerHealthAlert *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__event_timer_health_alert__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__EventTimerHealthAlert *
       timerpb__event_timer_health_alert__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__EventTimerHealthAlert *)
     protobuf_c_message_unpack (&timerpb__event_timer_health_alert__descriptor,
                                allocator, len, data);
}
void   timerpb__event_timer_health_alert__free_unpacked
                     (Timerpb__EventTimerHealthAlert *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__event_timer_health_alert__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   timerpb__event_lane_time__init
                     (Timerpb__EventLaneTime         *message)
{
  static const Timerpb__EventLaneTime init_value = TIMERPB__EVENT_LANE_TIME__INIT;
  *message = init_value;
}
size_t timerpb__event_lane_time__get_packed_size
                     (const Timerpb__EventLaneTime *message)
{
  assert(message->base.descriptor == &timerpb__event_lane_time__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t timerpb__event_lane_time__pack
                     (const Timerpb__EventLaneTime *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &timerpb__event_lane_time__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t timerpb__event_lane_time__pack_to_buffer
                     (const Timerpb__EventLaneTime *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &timerpb__event_lane_time__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Timerpb__EventLaneTime *
       timerpb__event_lane_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Timerpb__EventLaneTime *)
     protobuf_c_message_unpack (&timerpb__event_lane_time__descriptor,
                                allocator, len, data);
}
void   timerpb__event_lane_time__free_unpacked
                     (Timerpb__EventLaneTime *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &timerpb__event_lane_time__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor timerpb__timer_health__field_descriptors[25] =
{
  {
    "stamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerHealth, stamp),
    &timerpb__timer_time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chronyUsingPps",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Timerpb__TimerHealth, has_chronyusingpps),
    offsetof(Timerpb__TimerHealth, chronyusingpps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpsEmittingPps",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Timerpb__TimerHealth, has_gpsemittingpps),
    offsetof(Timerpb__TimerHealth, gpsemittingpps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ramFreeKB",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_ramfreekb),
    offsetof(Timerpb__TimerHealth, ramfreekb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpuTempC",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Timerpb__TimerHealth, has_cputempc),
    offsetof(Timerpb__TimerHealth, cputempc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpuUptime",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_cpuuptime),
    offsetof(Timerpb__TimerHealth, cpuuptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batteryMilliVolts",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_batterymillivolts),
    offsetof(Timerpb__TimerHealth, batterymillivolts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssid",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerHealth, ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "linkQuality",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerHealth, linkquality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signalLevel",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerHealth, signallevel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wirelessMac",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerHealth, wirelessmac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifiRss",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Timerpb__TimerHealth, has_wifirss),
    offsetof(Timerpb__TimerHealth, wifirss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxPublishAckMs",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_maxpublishackms),
    offsetof(Timerpb__TimerHealth, maxpublishackms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpsUptimeContiguous",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_gpsuptimecontiguous),
    offsetof(Timerpb__TimerHealth, gpsuptimecontiguous),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpsFlutter",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_gpsflutter),
    offsetof(Timerpb__TimerHealth, gpsflutter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifiIP",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerHealth, wifiip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "versionStamp",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Timerpb__TimerHealth, has_versionstamp),
    offsetof(Timerpb__TimerHealth, versionstamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "overlayFsEnabled",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Timerpb__TimerHealth, has_overlayfsenabled),
    offsetof(Timerpb__TimerHealth, overlayfsenabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpsUptimeTotal",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_gpsuptimetotal),
    offsetof(Timerpb__TimerHealth, gpsuptimetotal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpsInitialAcquisitionSecondsAfterBoot",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_gpsinitialacquisitionsecondsafterboot),
    offsetof(Timerpb__TimerHealth, gpsinitialacquisitionsecondsafterboot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buildEpoch",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Timerpb__TimerHealth, has_buildepoch),
    offsetof(Timerpb__TimerHealth, buildepoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gitDirty",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Timerpb__TimerHealth, has_gitdirty),
    offsetof(Timerpb__TimerHealth, gitdirty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpuIdlePercent",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_cpuidlepercent),
    offsetof(Timerpb__TimerHealth, cpuidlepercent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xmitCredits",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_xmitcredits),
    offsetof(Timerpb__TimerHealth, xmitcredits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mqttConnections",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerHealth, has_mqttconnections),
    offsetof(Timerpb__TimerHealth, mqttconnections),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_health__field_indices_by_name[] = {
  6,   /* field[6] = batteryMilliVolts */
  20,   /* field[20] = buildEpoch */
  1,   /* field[1] = chronyUsingPps */
  22,   /* field[22] = cpuIdlePercent */
  4,   /* field[4] = cpuTempC */
  5,   /* field[5] = cpuUptime */
  21,   /* field[21] = gitDirty */
  2,   /* field[2] = gpsEmittingPps */
  14,   /* field[14] = gpsFlutter */
  19,   /* field[19] = gpsInitialAcquisitionSecondsAfterBoot */
  13,   /* field[13] = gpsUptimeContiguous */
  18,   /* field[18] = gpsUptimeTotal */
  8,   /* field[8] = linkQuality */
  12,   /* field[12] = maxPublishAckMs */
  24,   /* field[24] = mqttConnections */
  17,   /* field[17] = overlayFsEnabled */
  3,   /* field[3] = ramFreeKB */
  9,   /* field[9] = signalLevel */
  7,   /* field[7] = ssid */
  0,   /* field[0] = stamp */
  16,   /* field[16] = versionStamp */
  15,   /* field[15] = wifiIP */
  11,   /* field[11] = wifiRss */
  10,   /* field[10] = wirelessMac */
  23,   /* field[23] = xmitCredits */
};
static const ProtobufCIntRange timerpb__timer_health__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 25 }
};
const ProtobufCMessageDescriptor timerpb__timer_health__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerHealth",
  "TimerHealth",
  "Timerpb__TimerHealth",
  "timerpb",
  sizeof(Timerpb__TimerHealth),
  25,
  timerpb__timer_health__field_descriptors,
  timerpb__timer_health__field_indices_by_name,
  1,  timerpb__timer_health__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_health__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_pulse__field_descriptors[5] =
{
  {
    "pinNumber",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerPulse, has_pinnumber),
    offsetof(Timerpb__TimerPulse, pinnumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stamp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerPulse, stamp),
    &timerpb__timer_time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane1",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Timerpb__TimerPulse, has_lane1),
    offsetof(Timerpb__TimerPulse, lane1),
    &timerpb__pin_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane2",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Timerpb__TimerPulse, has_lane2),
    offsetof(Timerpb__TimerPulse, lane2),
    &timerpb__pin_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pinName",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Timerpb__TimerPulse, has_pinname),
    offsetof(Timerpb__TimerPulse, pinname),
    &timerpb__pin_name__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_pulse__field_indices_by_name[] = {
  2,   /* field[2] = lane1 */
  3,   /* field[3] = lane2 */
  4,   /* field[4] = pinName */
  0,   /* field[0] = pinNumber */
  1,   /* field[1] = stamp */
};
static const ProtobufCIntRange timerpb__timer_pulse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor timerpb__timer_pulse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerPulse",
  "TimerPulse",
  "Timerpb__TimerPulse",
  "timerpb",
  sizeof(Timerpb__TimerPulse),
  5,
  timerpb__timer_pulse__field_descriptors,
  timerpb__timer_pulse__field_indices_by_name,
  1,  timerpb__timer_pulse__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_pulse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_pin__field_descriptors[4] =
{
  {
    "pinNumber",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Timerpb__TimerPin, has_pinnumber),
    offsetof(Timerpb__TimerPin, pinnumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stamp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerPin, stamp),
    &timerpb__timer_time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pinState",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Timerpb__TimerPin, has_pinstate),
    offsetof(Timerpb__TimerPin, pinstate),
    &timerpb__pin_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pinName",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Timerpb__TimerPin, has_pinname),
    offsetof(Timerpb__TimerPin, pinname),
    &timerpb__pin_name__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_pin__field_indices_by_name[] = {
  3,   /* field[3] = pinName */
  0,   /* field[0] = pinNumber */
  2,   /* field[2] = pinState */
  1,   /* field[1] = stamp */
};
static const ProtobufCIntRange timerpb__timer_pin__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor timerpb__timer_pin__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerPin",
  "TimerPin",
  "Timerpb__TimerPin",
  "timerpb",
  sizeof(Timerpb__TimerPin),
  4,
  timerpb__timer_pin__field_descriptors,
  timerpb__timer_pin__field_indices_by_name,
  1,  timerpb__timer_pin__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_pin__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__gps_tick_xref__field_descriptors[1] =
{
  {
    "timerTimeStamp",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Timerpb__GpsTickXref, n_timertimestamp),
    offsetof(Timerpb__GpsTickXref, timertimestamp),
    &timerpb__timer_time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__gps_tick_xref__field_indices_by_name[] = {
  0,   /* field[0] = timerTimeStamp */
};
static const ProtobufCIntRange timerpb__gps_tick_xref__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor timerpb__gps_tick_xref__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.GpsTickXref",
  "GpsTickXref",
  "Timerpb__GpsTickXref",
  "timerpb",
  sizeof(Timerpb__GpsTickXref),
  1,
  timerpb__gps_tick_xref__field_descriptors,
  timerpb__gps_tick_xref__field_indices_by_name,
  1,  timerpb__gps_tick_xref__number_ranges,
  (ProtobufCMessageInit) timerpb__gps_tick_xref__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_time_stamp__field_descriptors[3] =
{
  {
    "tick32",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerTimeStamp, has_tick32),
    offsetof(Timerpb__TimerTimeStamp, tick32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpsTime",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerTimeStamp, gpstime),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tick64",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Timerpb__TimerTimeStamp, has_tick64),
    offsetof(Timerpb__TimerTimeStamp, tick64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_time_stamp__field_indices_by_name[] = {
  1,   /* field[1] = gpsTime */
  0,   /* field[0] = tick32 */
  2,   /* field[2] = tick64 */
};
static const ProtobufCIntRange timerpb__timer_time_stamp__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor timerpb__timer_time_stamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerTimeStamp",
  "TimerTimeStamp",
  "Timerpb__TimerTimeStamp",
  "timerpb",
  sizeof(Timerpb__TimerTimeStamp),
  3,
  timerpb__timer_time_stamp__field_descriptors,
  timerpb__timer_time_stamp__field_indices_by_name,
  2,  timerpb__timer_time_stamp__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_time_stamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_data__field_descriptors[4] =
{
  {
    "timerPin",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerData, timerpin),
    &timerpb__timer_pin__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timerPulse",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerData, timerpulse),
    &timerpb__timer_pulse__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timerHealth",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerData, timerhealth),
    &timerpb__timer_health__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpsTickXref",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerData, gpstickxref),
    &timerpb__gps_tick_xref__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_data__field_indices_by_name[] = {
  3,   /* field[3] = gpsTickXref */
  2,   /* field[2] = timerHealth */
  0,   /* field[0] = timerPin */
  1,   /* field[1] = timerPulse */
};
static const ProtobufCIntRange timerpb__timer_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor timerpb__timer_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerData",
  "TimerData",
  "Timerpb__TimerData",
  "timerpb",
  sizeof(Timerpb__TimerData),
  4,
  timerpb__timer_data__field_descriptors,
  timerpb__timer_data__field_indices_by_name,
  1,  timerpb__timer_data__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_data_list__field_descriptors[4] =
{
  {
    "xmitTime",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerDataList, xmittime),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xmitMs",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Timerpb__TimerDataList, has_xmitms),
    offsetof(Timerpb__TimerDataList, xmitms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timerData",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Timerpb__TimerDataList, n_timerdata),
    offsetof(Timerpb__TimerDataList, timerdata),
    &timerpb__timer_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prevPubAckMs",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Timerpb__TimerDataList, has_prevpubackms),
    offsetof(Timerpb__TimerDataList, prevpubackms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_data_list__field_indices_by_name[] = {
  3,   /* field[3] = prevPubAckMs */
  2,   /* field[2] = timerData */
  1,   /* field[1] = xmitMs */
  0,   /* field[0] = xmitTime */
};
static const ProtobufCIntRange timerpb__timer_data_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor timerpb__timer_data_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerDataList",
  "TimerDataList",
  "Timerpb__TimerDataList",
  "timerpb",
  sizeof(Timerpb__TimerDataList),
  4,
  timerpb__timer_data_list__field_descriptors,
  timerpb__timer_data_list__field_indices_by_name,
  1,  timerpb__timer_data_list__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_data_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__elapsed_config__field_descriptors[3] =
{
  {
    "timerName",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Timerpb__ElapsedConfig, n_timername),
    offsetof(Timerpb__ElapsedConfig, timername),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxTravelMS",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__ElapsedConfig, has_maxtravelms),
    offsetof(Timerpb__ElapsedConfig, maxtravelms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minTravelMS",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__ElapsedConfig, has_mintravelms),
    offsetof(Timerpb__ElapsedConfig, mintravelms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__elapsed_config__field_indices_by_name[] = {
  1,   /* field[1] = maxTravelMS */
  2,   /* field[2] = minTravelMS */
  0,   /* field[0] = timerName */
};
static const ProtobufCIntRange timerpb__elapsed_config__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor timerpb__elapsed_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.ElapsedConfig",
  "ElapsedConfig",
  "Timerpb__ElapsedConfig",
  "timerpb",
  sizeof(Timerpb__ElapsedConfig),
  3,
  timerpb__elapsed_config__field_descriptors,
  timerpb__elapsed_config__field_indices_by_name,
  2,  timerpb__elapsed_config__number_ranges,
  (ProtobufCMessageInit) timerpb__elapsed_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_config__field_descriptors[12] =
{
  {
    "timerName",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerConfig, timername),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timerMqttClientId",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerConfig, timermqttclientid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "useGpsTime",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Timerpb__TimerConfig, has_usegpstime),
    offsetof(Timerpb__TimerConfig, usegpstime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orgId",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerConfig, orgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orgIz",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerConfig, orgiz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensorLogic",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Timerpb__TimerConfig, has_sensorlogic),
    offsetof(Timerpb__TimerConfig, sensorlogic),
    &timerpb__sensor_logic__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timerConfigLanePhotoEye",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerConfig, timerconfiglanephotoeye),
    &timerpb__timer_config_lane_photo_eye__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timerConfigOpposedStarter",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerConfig, timerconfigopposedstarter),
    &timerpb__timer_config_opposed_starter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxTrackSeconds",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerConfig, has_maxtrackseconds),
    offsetof(Timerpb__TimerConfig, maxtrackseconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deleted",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Timerpb__TimerConfig, has_deleted),
    offsetof(Timerpb__TimerConfig, deleted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerConfig, has_seq),
    offsetof(Timerpb__TimerConfig, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timerConfigRampPhotoEye",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerConfig, timerconfigrampphotoeye),
    &timerpb__timer_config_ramp_photo_eye__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_config__field_indices_by_name[] = {
  9,   /* field[9] = deleted */
  8,   /* field[8] = maxTrackSeconds */
  3,   /* field[3] = orgId */
  4,   /* field[4] = orgIz */
  5,   /* field[5] = sensorLogic */
  10,   /* field[10] = seq */
  6,   /* field[6] = timerConfigLanePhotoEye */
  7,   /* field[7] = timerConfigOpposedStarter */
  11,   /* field[11] = timerConfigRampPhotoEye */
  1,   /* field[1] = timerMqttClientId */
  0,   /* field[0] = timerName */
  2,   /* field[2] = useGpsTime */
};
static const ProtobufCIntRange timerpb__timer_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor timerpb__timer_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerConfig",
  "TimerConfig",
  "Timerpb__TimerConfig",
  "timerpb",
  sizeof(Timerpb__TimerConfig),
  12,
  timerpb__timer_config__field_descriptors,
  timerpb__timer_config__field_indices_by_name,
  1,  timerpb__timer_config__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_config_ramp_photo_eye__field_descriptors[1] =
{
  {
    "paddlesDropped",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerConfigRampPhotoEye, paddlesdropped),
    &timerpb__timer_config_opposed_position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_config_ramp_photo_eye__field_indices_by_name[] = {
  0,   /* field[0] = paddlesDropped */
};
static const ProtobufCIntRange timerpb__timer_config_ramp_photo_eye__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor timerpb__timer_config_ramp_photo_eye__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerConfigRampPhotoEye",
  "TimerConfigRampPhotoEye",
  "Timerpb__TimerConfigRampPhotoEye",
  "timerpb",
  sizeof(Timerpb__TimerConfigRampPhotoEye),
  1,
  timerpb__timer_config_ramp_photo_eye__field_descriptors,
  timerpb__timer_config_ramp_photo_eye__field_indices_by_name,
  1,  timerpb__timer_config_ramp_photo_eye__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_config_ramp_photo_eye__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_config_lane_photo_eye__field_descriptors[4] =
{
  {
    "maxCarLenMS",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerConfigLanePhotoEye, has_maxcarlenms),
    offsetof(Timerpb__TimerConfigLanePhotoEye, maxcarlenms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minCarLenMS",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerConfigLanePhotoEye, has_mincarlenms),
    offsetof(Timerpb__TimerConfigLanePhotoEye, mincarlenms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxPerfCount",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerConfigLanePhotoEye, has_maxperfcount),
    offsetof(Timerpb__TimerConfigLanePhotoEye, maxperfcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clearMS",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerConfigLanePhotoEye, has_clearms),
    offsetof(Timerpb__TimerConfigLanePhotoEye, clearms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_config_lane_photo_eye__field_indices_by_name[] = {
  3,   /* field[3] = clearMS */
  0,   /* field[0] = maxCarLenMS */
  2,   /* field[2] = maxPerfCount */
  1,   /* field[1] = minCarLenMS */
};
static const ProtobufCIntRange timerpb__timer_config_lane_photo_eye__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor timerpb__timer_config_lane_photo_eye__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerConfigLanePhotoEye",
  "TimerConfigLanePhotoEye",
  "Timerpb__TimerConfigLanePhotoEye",
  "timerpb",
  sizeof(Timerpb__TimerConfigLanePhotoEye),
  4,
  timerpb__timer_config_lane_photo_eye__field_descriptors,
  timerpb__timer_config_lane_photo_eye__field_indices_by_name,
  1,  timerpb__timer_config_lane_photo_eye__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_config_lane_photo_eye__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_config_opposed_starter__field_descriptors[3] =
{
  {
    "paddlesUp",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Timerpb__TimerConfigOpposedStarter, n_paddlesup),
    offsetof(Timerpb__TimerConfigOpposedStarter, paddlesup),
    &timerpb__timer_config_opposed_position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxTransitionMS",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerConfigOpposedStarter, has_maxtransitionms),
    offsetof(Timerpb__TimerConfigOpposedStarter, maxtransitionms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minTransitionMS",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Timerpb__TimerConfigOpposedStarter, has_mintransitionms),
    offsetof(Timerpb__TimerConfigOpposedStarter, mintransitionms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_config_opposed_starter__field_indices_by_name[] = {
  1,   /* field[1] = maxTransitionMS */
  2,   /* field[2] = minTransitionMS */
  0,   /* field[0] = paddlesUp */
};
static const ProtobufCIntRange timerpb__timer_config_opposed_starter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor timerpb__timer_config_opposed_starter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerConfigOpposedStarter",
  "TimerConfigOpposedStarter",
  "Timerpb__TimerConfigOpposedStarter",
  "timerpb",
  sizeof(Timerpb__TimerConfigOpposedStarter),
  3,
  timerpb__timer_config_opposed_starter__field_descriptors,
  timerpb__timer_config_opposed_starter__field_indices_by_name,
  1,  timerpb__timer_config_opposed_starter__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_config_opposed_starter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_config_opposed_position__field_descriptors[2] =
{
  {
    "pinState",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Timerpb__TimerConfigOpposedPosition, has_pinstate),
    offsetof(Timerpb__TimerConfigOpposedPosition, pinstate),
    &timerpb__pin_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pinName",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Timerpb__TimerConfigOpposedPosition, has_pinname),
    offsetof(Timerpb__TimerConfigOpposedPosition, pinname),
    &timerpb__pin_name__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_config_opposed_position__field_indices_by_name[] = {
  1,   /* field[1] = pinName */
  0,   /* field[0] = pinState */
};
static const ProtobufCIntRange timerpb__timer_config_opposed_position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor timerpb__timer_config_opposed_position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerConfigOpposedPosition",
  "TimerConfigOpposedPosition",
  "Timerpb__TimerConfigOpposedPosition",
  "timerpb",
  sizeof(Timerpb__TimerConfigOpposedPosition),
  2,
  timerpb__timer_config_opposed_position__field_descriptors,
  timerpb__timer_config_opposed_position__field_indices_by_name,
  1,  timerpb__timer_config_opposed_position__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_config_opposed_position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_event_list__field_descriptors[1] =
{
  {
    "timerEvent",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Timerpb__TimerEventList, n_timerevent),
    offsetof(Timerpb__TimerEventList, timerevent),
    &timerpb__timer_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_event_list__field_indices_by_name[] = {
  0,   /* field[0] = timerEvent */
};
static const ProtobufCIntRange timerpb__timer_event_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor timerpb__timer_event_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerEventList",
  "TimerEventList",
  "Timerpb__TimerEventList",
  "timerpb",
  sizeof(Timerpb__TimerEventList),
  1,
  timerpb__timer_event_list__field_descriptors,
  timerpb__timer_event_list__field_indices_by_name,
  1,  timerpb__timer_event_list__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_event_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__timer_event__field_descriptors[4] =
{
  {
    "eventLaneTime",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerEvent, eventlanetime),
    &timerpb__event_lane_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eventRacePaddleDrop",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerEvent, eventracepaddledrop),
    &timerpb__event_race_paddle_drop__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eventTimerAvailability",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerEvent, eventtimeravailability),
    &timerpb__event_timer_availability__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eventTimerHealthAlert",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__TimerEvent, eventtimerhealthalert),
    &timerpb__event_timer_health_alert__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__timer_event__field_indices_by_name[] = {
  0,   /* field[0] = eventLaneTime */
  1,   /* field[1] = eventRacePaddleDrop */
  2,   /* field[2] = eventTimerAvailability */
  3,   /* field[3] = eventTimerHealthAlert */
};
static const ProtobufCIntRange timerpb__timer_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor timerpb__timer_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.TimerEvent",
  "TimerEvent",
  "Timerpb__TimerEvent",
  "timerpb",
  sizeof(Timerpb__TimerEvent),
  4,
  timerpb__timer_event__field_descriptors,
  timerpb__timer_event__field_indices_by_name,
  1,  timerpb__timer_event__number_ranges,
  (ProtobufCMessageInit) timerpb__timer_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define timerpb__event_race_paddle_drop__field_descriptors NULL
#define timerpb__event_race_paddle_drop__field_indices_by_name NULL
#define timerpb__event_race_paddle_drop__number_ranges NULL
const ProtobufCMessageDescriptor timerpb__event_race_paddle_drop__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.EventRacePaddleDrop",
  "EventRacePaddleDrop",
  "Timerpb__EventRacePaddleDrop",
  "timerpb",
  sizeof(Timerpb__EventRacePaddleDrop),
  0,
  timerpb__event_race_paddle_drop__field_descriptors,
  timerpb__event_race_paddle_drop__field_indices_by_name,
  0,  timerpb__event_race_paddle_drop__number_ranges,
  (ProtobufCMessageInit) timerpb__event_race_paddle_drop__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define timerpb__event_timer_availability__field_descriptors NULL
#define timerpb__event_timer_availability__field_indices_by_name NULL
#define timerpb__event_timer_availability__number_ranges NULL
const ProtobufCMessageDescriptor timerpb__event_timer_availability__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.EventTimerAvailability",
  "EventTimerAvailability",
  "Timerpb__EventTimerAvailability",
  "timerpb",
  sizeof(Timerpb__EventTimerAvailability),
  0,
  timerpb__event_timer_availability__field_descriptors,
  timerpb__event_timer_availability__field_indices_by_name,
  0,  timerpb__event_timer_availability__number_ranges,
  (ProtobufCMessageInit) timerpb__event_timer_availability__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define timerpb__event_timer_health_alert__field_descriptors NULL
#define timerpb__event_timer_health_alert__field_indices_by_name NULL
#define timerpb__event_timer_health_alert__number_ranges NULL
const ProtobufCMessageDescriptor timerpb__event_timer_health_alert__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.EventTimerHealthAlert",
  "EventTimerHealthAlert",
  "Timerpb__EventTimerHealthAlert",
  "timerpb",
  sizeof(Timerpb__EventTimerHealthAlert),
  0,
  timerpb__event_timer_health_alert__field_descriptors,
  timerpb__event_timer_health_alert__field_indices_by_name,
  0,  timerpb__event_timer_health_alert__number_ranges,
  (ProtobufCMessageInit) timerpb__event_timer_health_alert__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor timerpb__event_lane_time__field_descriptors[4] =
{
  {
    "lane",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Timerpb__EventLaneTime, has_lane),
    offsetof(Timerpb__EventLaneTime, lane),
    &timerpb__pin_name__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noseTime",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__EventLaneTime, nosetime),
    &timerpb__timer_pin__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tailTime",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Timerpb__EventLaneTime, tailtime),
    &timerpb__timer_pin__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lanePairFound",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Timerpb__EventLaneTime, has_lanepairfound),
    offsetof(Timerpb__EventLaneTime, lanepairfound),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned timerpb__event_lane_time__field_indices_by_name[] = {
  0,   /* field[0] = lane */
  3,   /* field[3] = lanePairFound */
  1,   /* field[1] = noseTime */
  2,   /* field[2] = tailTime */
};
static const ProtobufCIntRange timerpb__event_lane_time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor timerpb__event_lane_time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "timerpb.EventLaneTime",
  "EventLaneTime",
  "Timerpb__EventLaneTime",
  "timerpb",
  sizeof(Timerpb__EventLaneTime),
  4,
  timerpb__event_lane_time__field_descriptors,
  timerpb__event_lane_time__field_indices_by_name,
  1,  timerpb__event_lane_time__number_ranges,
  (ProtobufCMessageInit) timerpb__event_lane_time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue timerpb__pin_state__enum_values_by_number[3] =
{
  { "CLEAR", "TIMERPB__PIN_STATE__CLEAR", 0 },
  { "BLOCKED", "TIMERPB__PIN_STATE__BLOCKED", 1 },
  { "UNKNOWN_STATE", "TIMERPB__PIN_STATE__UNKNOWN_STATE", 2 },
};
static const ProtobufCIntRange timerpb__pin_state__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex timerpb__pin_state__enum_values_by_name[3] =
{
  { "BLOCKED", 1 },
  { "CLEAR", 0 },
  { "UNKNOWN_STATE", 2 },
};
const ProtobufCEnumDescriptor timerpb__pin_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "timerpb.PinState",
  "PinState",
  "Timerpb__PinState",
  "timerpb",
  3,
  timerpb__pin_state__enum_values_by_number,
  3,
  timerpb__pin_state__enum_values_by_name,
  1,
  timerpb__pin_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue timerpb__pin_name__enum_values_by_number[5] =
{
  { "lane1", "TIMERPB__PIN_NAME__lane1", 1 },
  { "lane2", "TIMERPB__PIN_NAME__lane2", 2 },
  { "gpsHz", "TIMERPB__PIN_NAME__gpsHz", 3 },
  { "oneHz", "TIMERPB__PIN_NAME__oneHz", 4 },
  { "UNKNOWN_PIN", "TIMERPB__PIN_NAME__UNKNOWN_PIN", 9 },
};
static const ProtobufCIntRange timerpb__pin_name__value_ranges[] = {
{1, 0},{9, 4},{0, 5}
};
static const ProtobufCEnumValueIndex timerpb__pin_name__enum_values_by_name[5] =
{
  { "UNKNOWN_PIN", 4 },
  { "gpsHz", 2 },
  { "lane1", 0 },
  { "lane2", 1 },
  { "oneHz", 3 },
};
const ProtobufCEnumDescriptor timerpb__pin_name__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "timerpb.PinName",
  "PinName",
  "Timerpb__PinName",
  "timerpb",
  5,
  timerpb__pin_name__enum_values_by_number,
  5,
  timerpb__pin_name__enum_values_by_name,
  2,
  timerpb__pin_name__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue timerpb__sensor_logic__enum_values_by_number[3] =
{
  { "LanePhotoEyes", "TIMERPB__SENSOR_LOGIC__LanePhotoEyes", 1 },
  { "OpposedStarterReeds", "TIMERPB__SENSOR_LOGIC__OpposedStarterReeds", 2 },
  { "RampPhotoEyes", "TIMERPB__SENSOR_LOGIC__RampPhotoEyes", 3 },
};
static const ProtobufCIntRange timerpb__sensor_logic__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex timerpb__sensor_logic__enum_values_by_name[3] =
{
  { "LanePhotoEyes", 0 },
  { "OpposedStarterReeds", 1 },
  { "RampPhotoEyes", 2 },
};
const ProtobufCEnumDescriptor timerpb__sensor_logic__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "timerpb.SensorLogic",
  "SensorLogic",
  "Timerpb__SensorLogic",
  "timerpb",
  3,
  timerpb__sensor_logic__enum_values_by_number,
  3,
  timerpb__sensor_logic__enum_values_by_name,
  1,
  timerpb__sensor_logic__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
